# Generated by Django 6.0.7 on 2026-07-21 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrator'), ('SEK', 'Secretariat'), ('PREZ', 'President'), ('STF', 'Staff')], default='STF', max_length=5),
        ),
    ]
