# Generated by Django 6.0.7 on 2026-08-06 06:43

import apps.accounts.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_customuser_role"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="customuser",
            managers=[
                ("objects", apps.accounts.models.CustomUserManager()),
            ],
        ),
    ]
