# Generated by Django 6.0.7 on 2026-08-18 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_customuser_managers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("ADMIN", "Administrator"),
                    ("ADMW", "Administrator Worker"),
                    ("SEK", "Secretariat"),
                    ("PREZ", "President"),
                    ("STF", "Staff"),
                ],
                default="STF",
                max_length=5,
            ),
        ),
    ]
