# Generated by Django 6.0.7 on 2026-07-21 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbound_letters', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='status',
            field=models.CharField(choices=[('PND', 'Pending'), ('IPR', 'In Progress'), ('CMP', 'Completed')], db_index=True, default='PND', max_length=3),
        ),
        migrations.AlterField(
            model_name='inboundletter',
            name='status',
            field=models.CharField(choices=[('REG', 'Registered'), ('ASN', 'Assigned'), ('CMP', 'Completed'), ('ARC', 'Archived')], db_index=True, default='REG', max_length=3),
        ),
    ]
