# Generated by Django 6.0.7 on 2026-07-29 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inbound_letters", "0002_alter_assignment_status_alter_inboundletter_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inboundletter",
            name="tracking_code",
            field=models.CharField(editable=False, max_length=30, unique=True),
        ),
    ]
