# Generated by Django 6.0.7 on 2026-07-30 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inbound_letters", "0002_alter_assignment_status_alter_inboundletter_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="inboundletter",
            name="thumbnail",
            field=models.ImageField(
                blank=True, null=True, upload_to="inbound_thumbnails/"
            ),
        ),
    ]
