# Generated by Django 6.0.7 on 2026-08-01 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inbound_letters", "0003_alter_inboundletter_tracking_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="inboundletter",
            name="thumbnail",
            field=models.ImageField(
                blank=True, null=True, upload_to="inbound_thumbnails/"
            ),
        ),
    ]
