# Generated by Django 6.0.7 on 2026-08-14 06:28

from django.db import migrations


def backfill_original_ref_no(apps, schema_editor):
    InboundLetter = apps.get_model("inbound_letters", "InboundLetter")
    InboundLetter.objects.filter(
        original_ref_no__isnull=True
    ).update(original_ref_no="N/A")
    InboundLetter.objects.filter(original_ref_no="").update(original_ref_no="N/A")


class Migration(migrations.Migration):

    dependencies = [
        ("inbound_letters", "0005_inboundletter_category"),
    ]

    operations = [
        migrations.RunPython(backfill_original_ref_no, migrations.RunPython.noop),
    ]