# Generated by Django 6.0.7 on 2026-08-14 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inbound_letters", "0006_backfill_original_ref_no"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inboundletter",
            name="original_ref_no",
            field=models.CharField(max_length=100),
        ),
    ]
