# Generated by Django 6.0.7 on 2026-08-14 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inbound_letters", "0007_alter_inboundletter_original_ref_no"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inboundletter",
            name="category",
            field=models.CharField(
                choices=[
                    ("KVT", "Konvite"),
                    ("AUD", "Audensia"),
                    ("PED", "Pedidu (skala kiik)"),
                    ("PRP", "Proposta (skala boot)"),
                ],
                db_index=True,
                default="PED",
                max_length=3,
            ),
        ),
    ]