# Generated by Django 6.0.7 on 2026-08-14 07:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inbound_letters", "0008_alter_inboundletter_category"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="inboundletter",
            name="status",
            field=models.CharField(
                choices=[
                    ("REG", "Registered"),
                    ("APR", "Accepted"),
                    ("REJ", "Rejected"),
                    ("ASN", "Assigned"),
                    ("CMP", "Completed"),
                    ("ARC", "Archived"),
                ],
                db_index=True,
                default="REG",
                max_length=3,
            ),
        ),
        migrations.CreateModel(
            name="InboundDecision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "decision",
                    models.CharField(
                        choices=[("APR", "Accepted"), ("REJ", "Rejected")], max_length=3
                    ),
                ),
                ("comments", models.TextField(blank=True)),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "decided_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inbound_decisions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "letter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="decisions",
                        to="inbound_letters.inboundletter",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
    ]