# Generated by Django 6.0.7 on 2026-07-29 01:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OutboundLetter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tracking_code",
                    models.CharField(editable=False, max_length=30, unique=True),
                ),
                ("subject", models.CharField(max_length=255)),
                ("recipient_name", models.CharField(max_length=255)),
                ("recipient_institution", models.CharField(max_length=255)),
                ("recipient_address", models.TextField(blank=True)),
                ("original_ref_no", models.CharField(blank=True, max_length=100)),
                ("letter_date", models.DateField()),
                ("pdf_file", models.FileField(upload_to="outbound_pdfs/")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRF", "Draft"),
                            ("REV", "In Review"),
                            ("APR", "Approved"),
                            ("REJ", "Rejected"),
                            ("DSP", "Dispatched"),
                        ],
                        db_index=True,
                        default="DRF",
                        max_length=3,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="outbound_letters",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ApprovalStage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("REV", "Review"),
                            ("APR", "Approval"),
                            ("DSP", "Dispatch"),
                        ],
                        max_length=3,
                    ),
                ),
                (
                    "decision",
                    models.CharField(
                        choices=[
                            ("PND", "Pending"),
                            ("APR", "Approved"),
                            ("REJ", "Rejected"),
                        ],
                        default="PND",
                        max_length=3,
                    ),
                ),
                ("comments", models.TextField(blank=True)),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "reviewer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="approval_decisions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "letter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approval_stages",
                        to="outbound_letters.outboundletter",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
    ]
