# Generated by Django 6.0.7 on 2026-07-31 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("outbound_letters", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="outboundletter",
            name="thumbnail",
            field=models.ImageField(
                blank=True, null=True, upload_to="outbound_thumbnails/"
            ),
        ),
    ]
