# Generated by Django 6.0.7 on 2026-08-08 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outbound_letters', '0002_outboundletter_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='outboundletter',
            name='category',
            field=models.CharField(choices=[('ASU', 'Asuntu'), ('INF', 'Informasaun'), ('KVT', 'Konvite')], db_index=True, default='ASU', max_length=3),
        ),
    ]
