# Generated by Django 6.0.7 on 2026-08-14 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("outbound_letters", "0003_outboundletter_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="outboundletter",
            name="original_ref_no",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="outboundletter",
            name="recipient_address",
            field=models.TextField(),
        ),
    ]
